on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    types: ['opened', 'edited', 'reopened']

name: Check, Tests, Lints
jobs:

    buildAndLint:
        timeout-minutes: 10
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3
            - run: yarn install
            - run: yarn lerna bootstrap
            - run: yarn build
            - run: yarn lint

    Test:
        needs: [buildAndLint]
        timeout-minutes: 30
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]
                # Each app folder test will be run in parallel using the matrix
                folder: [client, programs, utils]

        steps:
            - uses: actions/checkout@v3
            - run: yarn install
            - run: yarn lerna bootstrap
            - run: yarn build
            - run: yarn test --roots "./packages/${{matrix.folder}}" --w 1
