on: [push, pull_request]
name: Check, Tests, Lints
jobs:
    lint-unit-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
            - run: yarn install
            - run: yarn lerna bootstrap
            - run: yarn build
            - run: yarn test
            - run: yarn lint
