on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    types: ['opened', 'edited', 'reopened']

name: Check, Tests, Lints
jobs:
    buildLintTest:
        timeout-minutes: 30
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]
                # Each app folder test will be run in parallel using the matrix
                folder: [./packages/client,./packages/log ./packages/programs,./packages/libp2p/direct-block ./packages/libp2p/direct-stream ./packages/libp2p/direct-sub ./packages/libp2p/libp2p-test-utils ./packages/libp2p/peerbit-libp2p ./packages/utils ./packages/server-node]

        steps:
            - uses: actions/checkout@v3
            - run: yarn install
            - run: yarn lerna bootstrap
            - run: yarn build
            - run: yarn lint
            - run: yarn test --roots ${{matrix.folder}}  --w 2
